"""
Problem model representing math problems in the content library.

Problems have bilingual questions (Bengali + English), answers, hints, and difficulty levels.
"""

from typing import Any

from sqlalchemy import JSON, CheckConstraint, Index, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from src.models.base import Base, TimestampMixin


class Hint:
    """Structured hint data (not a database model, stored as JSON).

    Attributes:
        hint_number: Which hint this is (1, 2, or 3).
        text_en: Hint text in English.
        text_bn: Hint text in Bengali.
        is_ai_generated: Whether hint was generated by Claude API.
    """

    def __init__(
        self,
        hint_number: int,
        text_en: str,
        text_bn: str,
        is_ai_generated: bool = False,
    ):
        """Initialize hint.

        Args:
            hint_number: Hint level (1=gentle, 2=medium, 3=detailed).
            text_en: English text.
            text_bn: Bengali text.
            is_ai_generated: Whether generated by AI or pre-written.
        """
        self.hint_number = hint_number
        self.text_en = text_en
        self.text_bn = text_bn
        self.is_ai_generated = is_ai_generated

    def to_dict(self) -> dict[str, Any]:
        """Convert hint to dictionary for JSON serialization."""
        return {
            "hint_number": self.hint_number,
            "text_en": self.text_en,
            "text_bn": self.text_bn,
            "is_ai_generated": self.is_ai_generated,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Hint":
        """Create hint from dictionary."""
        return cls(
            hint_number=data["hint_number"],
            text_en=data["text_en"],
            text_bn=data["text_bn"],
            is_ai_generated=data.get("is_ai_generated", False),
        )


class Problem(Base, TimestampMixin):
    """Problem in the content library.

    Each problem has:
    - Bilingual question (Bengali + English)
    - Correct answer
    - 3 Socratic hints
    - Difficulty level (1=easy, 2=medium, 3=hard)
    - Grade level (6, 7, or 8)
    - Topic classification

    Attributes:
        problem_id: Primary key.
        grade: Grade level (6, 7, or 8).
        topic: Subject area (e.g., "Profit & Loss", "Fractions").
        subtopic: Optional subcategory.
        question_en: Problem statement in English.
        question_bn: Problem statement in Bengali.
        answer: Correct answer (string format, e.g., "75 rupees" or "75").
        hints: List of 3 Hint objects stored as JSON.
        difficulty: Difficulty level (1=easy, 2=medium, 3=hard).
        estimated_time_minutes: Expected time to solve.
        created_at: Timestamp when problem added.
        updated_at: Timestamp when problem last modified.
    """

    __tablename__ = "problems"

    # Primary key
    problem_id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
        autoincrement=True,
        comment="Unique problem identifier",
    )

    # Classification
    grade: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        comment="Grade level (6, 7, or 8)",
    )

    topic: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        comment="Topic category (e.g., 'Profit & Loss')",
    )

    subtopic: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        comment="Optional subtopic classification",
    )

    # Content (bilingual)
    question_en: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Problem statement in English",
    )

    question_bn: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Problem statement in Bengali",
    )

    answer: Mapped[str] = mapped_column(
        String(500),
        nullable=False,
        comment="Correct answer (accept format: '75 rupees' or '75')",
    )

    # Hints stored as JSON array of Hint objects
    hints: Mapped[list[dict[str, Any]]] = mapped_column(
        JSON,
        nullable=False,
        comment="Array of 3 hints (JSON format)",
    )

    # Metadata
    difficulty: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        comment="Difficulty level (1=easy, 2=medium, 3=hard)",
    )

    estimated_time_minutes: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        server_default="5",
        comment="Estimated time to solve in minutes",
    )

    # Constraints
    __table_args__ = (
        CheckConstraint(
            "grade IN (6, 7, 8)",
            name="ck_problems_grade_valid",
        ),
        CheckConstraint(
            "difficulty IN (1, 2, 3)",
            name="ck_problems_difficulty_valid",
        ),
        CheckConstraint(
            "estimated_time_minutes > 0",
            name="ck_problems_time_positive",
        ),
        Index("idx_problems_grade_topic", "grade", "topic"),
        Index("idx_problems_difficulty", "difficulty"),
    )

    def get_hints(self) -> list[Hint]:
        """Get hints as Hint objects.

        Returns:
            List of 3 Hint objects.
        """
        return [Hint.from_dict(hint_dict) for hint_dict in self.hints]

    def get_question(self, language: str) -> str:
        """Get question in specified language.

        Args:
            language: 'en' for English, 'bn' for Bengali.

        Returns:
            Question text in requested language.
        """
        if language == "bn":
            return self.question_bn
        return self.question_en

    def __repr__(self) -> str:
        """String representation of Problem."""
        return (
            f"<Problem(id={self.problem_id}, grade={self.grade}, "
            f"topic='{self.topic}', difficulty={self.difficulty})>"
        )
